apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-service
  labels:
    app: spring-boot-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spring-boot-service
    spec:
      containers:
        - image: dus815/spring-boot-demo:0.0.2
          imagePullPolicy: Always
          name: spring-demo
          ports:
            - containerPort: 8080
              protocol: TCP