apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
  labels:
    app: spring-boot-service
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: spring-boot-service
  type: LoadBalancer